<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\Image\NovaPasta\**" />
    <Content Remove="wwwroot\Image\NovaPasta\**" />
    <EmbeddedResource Remove="wwwroot\Image\NovaPasta\**" />
    <None Remove="wwwroot\Image\NovaPasta\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Image\download.png" />
    <Content Remove="wwwroot\Image\Fachada.jpeg" />
    <Content Remove="wwwroot\Image\Fachada.png" />
    <Content Remove="wwwroot\Image\Fachada2.jpg" />
    <Content Remove="wwwroot\Image\Fachada2.png" />
    <Content Remove="wwwroot\Image\Fachada3.jpg" />
    <Content Remove="wwwroot\Image\FachadaCortada.jpg" />
    <Content Remove="wwwroot\Image\Gratis.jfif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.26.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\MyStyle.css" />
  </ItemGroup>

</Project>
